-- Atena: armazenamento de memória episódica multi-tenant
-- Pré-requisito: projeto Supabase com a extensão pgvector disponível.
-- O script é idempotente e pode ser aplicado como uma migração.

begin;

-- A extensão costuma existir no schema extensions em projetos Supabase.
create extension if not exists vector with schema extensions;

create table if not exists public.atena_memory_chunks (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  content_hash text not null,
  source_path text not null,
  source_sha256 text,
  chunk_no integer not null default 0,
  content text not null,
  approved boolean not null default false,
  embedding_model text,
  embedding extensions.vector(384),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  content_tsv tsvector generated always as (
    to_tsvector('simple', coalesce(content, ''))
  ) stored,
  constraint atena_memory_chunks_tenant_id_nonempty
    check (length(trim(tenant_id)) > 0),
  constraint atena_memory_chunks_content_hash_nonempty
    check (length(trim(content_hash)) > 0),
  constraint atena_memory_chunks_chunk_no_nonnegative
    check (chunk_no >= 0),
  constraint atena_memory_chunks_tenant_content_unique
    unique (tenant_id, content_hash)
);

-- Compatibilidade com instalações anteriores que já criaram a tabela.
alter table public.atena_memory_chunks
  add column if not exists tenant_id text;

update public.atena_memory_chunks
set tenant_id = 'atena-programming'
where tenant_id is null;

alter table public.atena_memory_chunks
  alter column tenant_id set default 'atena-programming',
  alter column tenant_id set not null;

alter table public.atena_memory_chunks
  add column if not exists source_sha256 text,
  add column if not exists chunk_no integer default 0,
  add column if not exists approved boolean default false,
  add column if not exists embedding_model text,
  add column if not exists embedding extensions.vector(384),
  add column if not exists metadata jsonb default '{}'::jsonb,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

-- Garante os valores padrão/not-null nas colunas adicionadas à instalação legada.
update public.atena_memory_chunks
set
  chunk_no = coalesce(chunk_no, 0),
  approved = coalesce(approved, false),
  metadata = coalesce(metadata, '{}'::jsonb),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now())
where
  chunk_no is null
  or approved is null
  or metadata is null
  or created_at is null
  or updated_at is null;

alter table public.atena_memory_chunks
  alter column chunk_no set not null,
  alter column approved set not null,
  alter column metadata set not null,
  alter column created_at set not null,
  alter column updated_at set not null;

-- Recria a coluna de texto completo caso a instalação legada ainda não a tenha.
alter table public.atena_memory_chunks
  add column if not exists content_tsv tsvector generated always as (
    to_tsvector('simple', coalesce(content, ''))
  ) stored;

-- Índices de isolamento e acesso.
create index if not exists atena_memory_chunks_tenant_created_idx
  on public.atena_memory_chunks (tenant_id, created_at desc);

create unique index if not exists atena_memory_chunks_tenant_content_hash_uidx
  on public.atena_memory_chunks (tenant_id, content_hash);

create index if not exists atena_memory_chunks_tenant_approved_idx
  on public.atena_memory_chunks (tenant_id, approved)
  where approved = true;

create index if not exists atena_memory_chunks_content_tsv_gin
  on public.atena_memory_chunks using gin (content_tsv);

-- O índice HNSW acelera distância por cosseno. O predicado evita indexar nulos.
create index if not exists atena_memory_chunks_embedding_hnsw
  on public.atena_memory_chunks
  using hnsw (embedding vector_cosine_ops)
  where embedding is not null;

-- Atualiza updated_at em alterações.
create or replace function public.atena_memory_chunks_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists atena_memory_chunks_updated_at on public.atena_memory_chunks;
create trigger atena_memory_chunks_updated_at
before update on public.atena_memory_chunks
for each row execute function public.atena_memory_chunks_set_updated_at();

-- RLS: cada sessão deve definir o tenant no JWT como app.tenant_id.
-- O serviço de sincronização pode usar a chave service_role, mas a RPC ainda
-- aplica o filtro explícito p_tenant_id e não depende apenas do RLS.
alter table public.atena_memory_chunks enable row level security;

 drop policy if exists atena_memory_chunks_select_tenant on public.atena_memory_chunks;
create policy atena_memory_chunks_select_tenant
on public.atena_memory_chunks
for select
to authenticated
using (
  tenant_id = nullif((auth.jwt() ->> 'tenant_id'), '')
);

drop policy if exists atena_memory_chunks_insert_tenant on public.atena_memory_chunks;
create policy atena_memory_chunks_insert_tenant
on public.atena_memory_chunks
for insert
to authenticated
with check (
  tenant_id = nullif((auth.jwt() ->> 'tenant_id'), '')
);

drop policy if exists atena_memory_chunks_update_tenant on public.atena_memory_chunks;
create policy atena_memory_chunks_update_tenant
on public.atena_memory_chunks
for update
to authenticated
using (
  tenant_id = nullif((auth.jwt() ->> 'tenant_id'), '')
)
with check (
  tenant_id = nullif((auth.jwt() ->> 'tenant_id'), '')
);

drop policy if exists atena_memory_chunks_delete_tenant on public.atena_memory_chunks;
create policy atena_memory_chunks_delete_tenant
on public.atena_memory_chunks
for delete
to authenticated
using (
  tenant_id = nullif((auth.jwt() ->> 'tenant_id'), '')
);

-- Busca híbrida. p_tenant_id é obrigatório para impedir chamadas sem escopo.
-- O filtro aparece dentro dos CTEs antes do ranking e do LIMIT.
create or replace function public.search_atena_memory_hybrid(
  p_tenant_id text,
  p_query_embedding extensions.vector(384),
  p_query_text text,
  p_match_count integer default 10,
  p_vector_weight real default 0.7,
  p_text_weight real default 0.3,
  p_approved_only boolean default false
)
returns table (
  id bigint,
  tenant_id text,
  content_hash text,
  source_path text,
  content text,
  approved boolean,
  metadata jsonb,
  vector_similarity double precision,
  text_rank real,
  hybrid_score double precision
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  with params as (
    select
      nullif(trim(p_tenant_id), '') as tenant_id,
      p_query_embedding as query_embedding,
      nullif(trim(coalesce(p_query_text, '')), '') as query_text,
      least(greatest(coalesce(p_match_count, 10), 1), 50) as match_count,
      greatest(coalesce(p_vector_weight, 0.7), 0)::double precision as vector_weight,
      greatest(coalesce(p_text_weight, 0.3), 0)::double precision as text_weight,
      coalesce(p_approved_only, false) as approved_only
  ),
  vector_candidates as (
    select
      c.id,
      1 - (c.embedding <=> p.query_embedding) as vector_similarity
    from public.atena_memory_chunks c
    cross join params p
    where
      c.tenant_id = p.tenant_id
      and c.embedding is not null
      and (not p.approved_only or c.approved = true)
      and p.query_embedding is not null
    order by c.embedding <=> p.query_embedding
    limit 100
  ),
  text_candidates as (
    select
      c.id,
      ts_rank_cd(c.content_tsv, websearch_to_tsquery('simple', p.query_text)) as text_rank
    from public.atena_memory_chunks c
    cross join params p
    where
      c.tenant_id = p.tenant_id
      and p.query_text is not null
      and c.content_tsv @@ websearch_to_tsquery('simple', p.query_text)
      and (not p.approved_only or c.approved = true)
    order by ts_rank_cd(c.content_tsv, websearch_to_tsquery('simple', p.query_text)) desc
    limit 100
  ),
  scores as (
    select
      coalesce(v.id, t.id) as id,
      coalesce(v.vector_similarity, 0)::double precision as vector_similarity,
      coalesce(t.text_rank, 0)::real as text_rank,
      (
        coalesce(v.vector_similarity, 0) * p.vector_weight
        + coalesce(t.text_rank, 0) * p.text_weight
      )::double precision as hybrid_score,
      p.tenant_id
    from vector_candidates v
    full outer join text_candidates t on t.id = v.id
    cross join params p
  )
  select
    c.id,
    c.tenant_id,
    c.content_hash,
    c.source_path,
    c.content,
    c.approved,
    c.metadata,
    s.vector_similarity,
    s.text_rank,
    s.hybrid_score
  from scores s
  join public.atena_memory_chunks c
    on c.id = s.id
   and c.tenant_id = s.tenant_id
  order by s.hybrid_score desc
  limit (select match_count from params);
$$;

commit;
